# Generated by Django 5.2.2 on 2025-07-16 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Annotation Label')),
                ('coordinates', models.JSONField(help_text='Polygon or point data for the annotation', verbose_name='Coordinates')),
                ('area_size', models.FloatField(blank=True, default=None, help_text='Size of the area in square units', null=True, verbose_name='Area Size')),
                ('annotation_type', models.CharField(help_text='Shape Type (e.g., polygon, point or rectangle)', max_length=50, verbose_name='Annotation Type')),
                ('width', models.FloatField(blank=True, default=None, help_text='Width of the annotation in sqft', null=True, verbose_name='Width')),
                ('height', models.FloatField(blank=True, default=None, help_text='Height of the annotation in sqft', null=True, verbose_name='Height')),
                ('confidence_score', models.FloatField(blank=True, default=None, help_text='Confidence score of the annotation', null=True, verbose_name='Prediction Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='plans.blueprintimage')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_materials', to='annotations.annotation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_materials', to='materials.material')),
            ],
            options={
                'unique_together': {('annotation', 'material')},
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='materials',
            field=models.ManyToManyField(related_name='annotations', through='annotations.AnnotationMaterial', to='materials.material'),
        ),
        migrations.CreateModel(
            name='FloorAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Floor', max_length=255, verbose_name='Floor Annotation Label')),
                ('coordinates', models.JSONField(help_text='Polygon or point data for the annotation', verbose_name='Coordinates')),
                ('annotation_type', models.CharField(help_text='Shape Type (e.g., polygon, point or rectangle)', max_length=50, verbose_name='Annotation Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_annotations', to='plans.blueprintimage')),
            ],
            options={
                'verbose_name': 'Floor Annotation',
                'verbose_name_plural': 'Floor Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WallAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Wall Annotation Label')),
                ('coordinates', models.JSONField(help_text='Rectangle point for the annotation', verbose_name='Coordinates')),
                ('annotation_type', models.CharField(help_text='Shape Type (e.g., polygon, point or rectangle)', max_length=50, verbose_name='Annotation Type')),
                ('lenght_ft', models.FloatField(blank=True, default=None, help_text='Length of the wall in feet', null=True, verbose_name='Length in Feet')),
                ('thickness_ft', models.FloatField(blank=True, default=None, help_text='Thickness of the wall in feet', null=True, verbose_name='Thickness in Feet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_annotations', to='plans.blueprintimage')),
            ],
            options={
                'verbose_name': 'Wall Annotation',
                'verbose_name_plural': 'Wall Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WallAnnotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('wall_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_annotation_materials', to='annotations.wallannotation')),
            ],
            options={
                'unique_together': {('wall_annotation', 'material')},
            },
        ),
        migrations.AddField(
            model_name='wallannotation',
            name='materials',
            field=models.ManyToManyField(related_name='wall_annotations', through='annotations.WallAnnotationMaterial', to='materials.material'),
        ),
        migrations.CreateModel(
            name='WindowAndDoorAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Window and Door Annotation Label')),
                ('coordinates', models.JSONField(help_text='Polygon or point data for the annotation', verbose_name='Coordinates')),
                ('annotation_type', models.CharField(help_text='Shape Type (e.g., polygon, point or rectangle)', max_length=50, verbose_name='Annotation Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_and_door_annotations', to='plans.blueprintimage')),
            ],
            options={
                'verbose_name': 'Window & Door Annotation',
                'verbose_name_plural': 'Windows & Doors Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WindowAndDoorAnnotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('window_and_door_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_and_door_annotation_materials', to='annotations.windowanddoorannotation')),
            ],
            options={
                'unique_together': {('window_and_door_annotation', 'material')},
            },
        ),
        migrations.AddField(
            model_name='windowanddoorannotation',
            name='materials',
            field=models.ManyToManyField(related_name='window_and_door_annotations', through='annotations.WindowAndDoorAnnotationMaterial', to='materials.material'),
        ),
    ]
