# Generated by Django 5.2.2 on 2025-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallannotation',
            name='area',
            field=models.FloatField(blank=True, default=None, help_text='Size of the area in square units', null=True, verbose_name='Area Size'),
        ),
    ]
