# Generated by Django 5.2.2 on 2025-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_wallannotation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowanddoorannotation',
            name='breadth_ft',
            field=models.FloatField(blank=True, default=None, help_text='Breadth of the wall in feet', null=True, verbose_name='Breadth in Feet'),
        ),
        migrations.AddField(
            model_name='windowanddoorannotation',
            name='lenght_ft',
            field=models.FloatField(blank=True, default=None, help_text='Length of the wall in feet', null=True, verbose_name='Length in Feet'),
        ),
        migrations.AlterField(
            model_name='wallannotation',
            name='area',
            field=models.FloatField(blank=True, default=None, help_text='Size of the area in square units', null=True, verbose_name='Area'),
        ),
    ]
