# Generated by Django 5.2.2 on 2025-07-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_windowanddoorannotation_breadth_ft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowanddoorannotation',
            old_name='lenght_ft',
            new_name='length_ft',
        ),
    ]
