# Generated by Django 5.2.2 on 2025-07-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_rename_lenght_ft_windowanddoorannotation_length_ft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallannotation',
            old_name='lenght_ft',
            new_name='length_ft',
        ),
    ]
