# Generated by Django 5.2.2 on 2025-07-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_rename_lenght_ft_wallannotation_length_ft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='area_size',
            new_name='area',
        ),
    ]
