# Generated by Django 5.2.2 on 2025-08-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_rename_area_size_annotation_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloorAnnotation',
        ),
    ]
