# Generated by Django 5.2.2 on 2025-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_delete_floorannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmaterial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallannotationmaterial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windowanddoorannotationmaterial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
