# Generated by Django 5.2.2 on 2025-11-11 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintExtraInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv_data', models.JSONField(help_text='Imported CSV data as JSON', verbose_name='CSV Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='plans.blueprintimage')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_csv_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blueprint Extra Info',
                'verbose_name_plural': 'Blueprint Extra Info',
                'ordering': ['-created_at'],
            },
        ),
    ]
