# Generated by Django 5.2.2 on 2025-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimators', '0002_blueprintextrainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintextrainfo',
            name='csv_data',
            field=models.JSONField(blank=True, default=list, help_text='Imported CSV data as JSON', null=True, verbose_name='CSV Data'),
        ),
    ]
