# Generated by Django 5.2.2 on 2025-07-16 02:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Blueprint Title')),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='blueprints/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('elevation', 'Elevation'), ('plan', 'Plan')], default='plan', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='projects.project')),
            ],
            options={
                'verbose_name': 'Blueprint',
                'verbose_name_plural': 'Blueprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default='Untitled Image', upload_to='blueprints/images/')),
                ('dpi', models.IntegerField(blank=True, default=None, help_text='Dots per inch of the image', null=True, verbose_name='DPI')),
                ('scale', models.FloatField(blank=True, default=2.1, help_text='Scale of the image in inches per pixel', null=True, verbose_name='Scale')),
                ('floor_json_file', models.FileField(blank=True, null=True, upload_to='json/floor/')),
                ('wall_json_file', models.FileField(blank=True, null=True, upload_to='json/wall/')),
                ('window_json_file', models.FileField(blank=True, null=True, upload_to='json/window&door/')),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.blueprint', verbose_name='Blueprint Title')),
            ],
            options={
                'verbose_name': 'Blueprint Image',
                'verbose_name_plural': 'Blueprint Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
